name: pywinds
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-pack
  - netcdf4
  - numpy
  - pip
  - pyproj
  - pyresample
  - python
  - sphinx
  - xarray
  - pip:
    - git+https://github.com/wroberts4/pywinds.git@master